// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cmd(arg1) {
  return window['go']['app']['App']['Cmd'](arg1);
}
